record=76 variable=y compress=y key=3 page=1024

position=1 length=4 duplicates=n modifiable=n type=autoinc alternate=n
null=n segment=n

position=5 length=4 duplicates=y modifiable=y type=unsigned alternate=n
null=n segment=y 
position=75 length=2 duplicates=y modifiable=y type=unsigned alternate=n
null=n segment=n

position=9 length=2 duplicates=y modifiable=y type=unsigned alternate=n
null=n segment=y
position=11 length=64 duplicates=y modifiable=y type=zstring alternate=n
null=n segment=y
position=75 length=2 duplicates=y modifiable=y type=unsigned alternate=n
null=n segment=n


