@echo off
setlocal

set "V200_TEST_ROOT=%~dp0"
set "V200_ROOT=%V200_TEST_ROOT%.."
set "REPO_ROOT=%V200_TEST_ROOT%..\.."

if "%TEST_PROFILE%"=="" set "TEST_PROFILE=DBG"

if /I "%TEST_PROFILE%"=="DBG" (
  set "DEFAULT_BUILD_ROOT=%V200_ROOT%\V200_32.DBG"
) else if /I "%TEST_PROFILE%"=="OPT" (
  set "DEFAULT_BUILD_ROOT=%V200_ROOT%\V200_32.OPT"
) else (
  echo ERROR: Unsupported TEST_PROFILE=%TEST_PROFILE%. Use DBG or OPT.
  exit /b 1
)

if "%TEST_BUILD_ROOT%"=="" set "TEST_BUILD_ROOT=%DEFAULT_BUILD_ROOT%"
if "%TEST_LIB_ROOT%"=="" set "TEST_LIB_ROOT=%TEST_BUILD_ROOT%"
if "%TEST_DLL_ROOT%"=="" set "TEST_DLL_ROOT=%TEST_BUILD_ROOT%"

set "TEST_SRC_ROOT=%V200_ROOT%\V200.SRC"
set "TEST_INCLUDE_ROOT=%TEST_SRC_ROOT%\Include"

endlocal & (
  set "V200_TEST_ROOT=%V200_TEST_ROOT%"
  set "V200_ROOT=%V200_ROOT%"
  set "TEST_PROFILE=%TEST_PROFILE%"
  set "TEST_BUILD_ROOT=%TEST_BUILD_ROOT%"
  set "TEST_LIB_ROOT=%TEST_LIB_ROOT%"
  set "TEST_DLL_ROOT=%TEST_DLL_ROOT%"
  set "TEST_SRC_ROOT=%TEST_SRC_ROOT%"
  set "TEST_INCLUDE_ROOT=%TEST_INCLUDE_ROOT%"
)
exit /b 0
