//////////////////////////////////////////////////////////////////////////////
//
//  Windows Socket access functions - Header file
//
// $Header:   F:/clinicum/include/rev/socket.hpv   1.0   09 Oct 1998 18:46:58   Wolfgang  $
// $Log:   F:/clinicum/include/rev/socket.hpv  $
// 
//    Rev 1.0   09 Oct 1998 18:46:58   Wolfgang
// Initial revision.
//
/////////////////////////////////////////////////////////////////////////////

extern void CheckSocketEvent (WPARAM wP, LPARAM lP);

