record=159 variable=y compress=y key=6 page=1024

position=1 length=4 duplicates=n modifiable=n type=autoinc alternate=n
null=n segment=n

position=5 length=21 duplicates=y modifiable=n type=zstring alternate=n
null=n segment=y 
position=26 length=64 duplicates=y modifiable=n type=zstring alternate=y
null=n segment=y
position=158 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=n

position=5 length=21 duplicates=y modifiable=n type=zstring alternate=n
null=n segment=y 
position=90 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=y
position=158 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=n

position=5 length=21 duplicates=y modifiable=n type=zstring alternate=n
null=n segment=y 
position=90 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=y
position=92 length=64 duplicates=y modifiable=n type=zstring alternate=y
null=n segment=y
position=158 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=n

position=5 length=21 duplicates=y modifiable=n type=zstring alternate=n
null=n segment=y 
position=90 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=y
position=156 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=y
position=158 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=n

position=5 length=21 duplicates=y modifiable=n type=zstring alternate=n
null=n segment=y
position=158 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=n

name=SOFTWORK.ALT

