record=232 variable=y compress=y key=2 page=1024

position=1 length=4 duplicates=n modifiable=n type=autoinc alternate=n
null=n segment=n

position=5 length=1 duplicates=y modifiable=n type=string alternate=n
null=n segment=y
position=6 length=64 duplicates=y modifiable=n type=zstring alternate=n
null=n segment=y 
position=70 length=2 duplicates=y modifiable=n type=unsigned alternate=n
null=n segment=n

