record=74 variable=y compress=y key=2 page=1024

position=1 length=4 duplicates=n modifiable=n type=autoinc alternate=n
null=n segment=n

position=5 length=2 duplicates=n modifiable=n type=unsigned alternate=n
null=n segment=y 
position=7 length=64 duplicates=n modifiable=n type=zstring alternate=n
null=n segment=y 
position=71 length=2 duplicates=n modifiable=n type=unsigned alternate=n
null=n segment=n

