[Script]
include=__includepath__\
source=__sourcepath__\
debug=__sourcepath__\sdi\
template=__sourcepath__\

[Config]
ReadProgCnf=no
SlVers=no

[Fonts]
ReadFormatDesc=no
FormatDescription=__fontpath__\fi%d%c.txt
WriteFormatDesc=yes
StatusBarHeight=15

[Schiebelehre]
Port=LPT1
MpxDelay=250
AnzTry=8
MaxDelay=2
UserIBM=yes

[ScanDecomp]
X=1.0
Y=1.0

[Documents]
ReadList=no

[Data]
UseMultiUserBtrieve=yes
UseSema=yes

[Tools]
UseTools=yes
;InstallObserver=DSYS->DMWS
;SwitchDos=yes
;noLogin=yes

[Profile]
Check=Fields,Lines,Patterns,Setconn,Update,Show
GetBreak=-1

[DataBase]
AllDLLs=MV1,MV2,MV3
MV1=dbbtrv.dll
MV2=ddsodbc.dll
MV3=ddsseq.dll
DefaultDLL=MV2
ResourceDLL=MV3
SeqPath=C:\ipos_kernel\V200\V200.TEST\SEQ\

[Tables]
AnzTableDefs=1000

;[Startup]
;Startprg=UPD001.TXT

[ErrorHandling]
AutoAbortTime=3
